"use client";
import { useState } from "react";
import { ChevronRight, Bot } from "lucide-react";
import { Topbar } from "@/components/shell";
import { Badge, Card, MetricLabel, Select, priorityTone, statusTone, riskTone, Button } from "@/components/ui";
import { demoTests } from "@/lib/demo";
import { cn } from "@/lib/utils";

export default function TestCases() {
  const [open, setOpen] = useState<string | null>(demoTests[1].id);
  const [category, setCategory] = useState("all");
  const rows = demoTests.filter(t => category === "all" || t.category === category);

  return (
    <>
      <Topbar title="Test cases" subtitle={`${demoTests.length} shown · 428 in suite`} />
      <main className="p-6">
        <div className="mb-4 flex items-center gap-2">
          <Select value={category} onChange={e => setCategory(e.target.value)}>
            <option value="all">All categories</option>
            {["functional","negative","edge","integration","e2e","security","accessibility","api"].map(c =>
              <option key={c} value={c}>{c}</option>)}
          </Select>
          <div className="flex-1" />
          <Button variant="outline" size="sm">Export suite</Button>
          <Button size="sm"><Bot size={14} /> Generate automation</Button>
        </div>

        <div className="card divide-y divide-line overflow-hidden p-0">
          {rows.map((t) => (
            <div key={t.id}>
              <button
                onClick={() => setOpen(open === t.id ? null : t.id)}
                className="flex w-full items-center gap-4 px-4 py-3 text-left transition-colors hover:bg-raised"
              >
                <ChevronRight size={14} className={cn("shrink-0 text-muted transition-transform", open === t.id && "rotate-90")} />
                <span className="w-28 shrink-0 font-mono text-[12px] text-accent">{t.test_key}</span>
                <span className="flex-1 truncate text-[13.5px] font-medium">{t.title}</span>
                <Badge mono>{t.category}</Badge>
                <Badge tone={priorityTone(t.priority)} mono>{t.priority}</Badge>
                <Badge tone={riskTone(t.risk_level)} mono>{t.risk_level}</Badge>
                <Badge tone={statusTone(t.status)} mono>{t.status.replace("_", " ")}</Badge>
              </button>

              {open === t.id && (
                <div className="grid gap-5 border-t border-line bg-raised/50 px-11 py-5 lg:grid-cols-[1fr_260px]">
                  <div>
                    <MetricLabel>Objective</MetricLabel>
                    <p className="mt-1 text-[13.5px] leading-relaxed">{t.objective}</p>

                    <MetricLabel className="mt-4">Preconditions</MetricLabel>
                    <ul className="mt-1 list-disc space-y-0.5 pl-4 text-[13px] text-muted">
                      {t.preconditions.map((p, i) => <li key={i}>{p}</li>)}
                    </ul>

                    <MetricLabel className="mt-4">Steps</MetricLabel>
                    <ol className="mt-2 space-y-2">
                      {t.steps.map((s) => (
                        <li key={s.step} className="grid grid-cols-[24px_1fr_1fr] gap-3 text-[13px]">
                          <span className="font-mono text-muted">{String(s.step).padStart(2, "0")}</span>
                          <span>{s.action}</span>
                          <span className="text-muted">↳ {s.expected}</span>
                        </li>
                      ))}
                    </ol>

                    <MetricLabel className="mt-4">Expected result</MetricLabel>
                    <p className="mt-1 text-[13px] text-pass">{t.expected_result}</p>
                  </div>

                  <div className="space-y-4">
                    <div>
                      <MetricLabel>Automation readiness</MetricLabel>
                      <p className="mt-1 font-mono text-2xl tabular-nums">{t.automation_readiness}%</p>
                    </div>
                    <div>
                      <MetricLabel>Traceability</MetricLabel>
                      <div className="mt-1.5 flex flex-wrap gap-1.5">
                        {t.traceability.map(id => <Badge key={id} tone="info" mono>{id}</Badge>)}
                      </div>
                    </div>
                    <div>
                      <MetricLabel>Provenance</MetricLabel>
                      <p className="mt-1 flex items-center gap-1.5 text-[12.5px] text-muted">
                        <Bot size={13} className="text-accent" /> Generated by Argus · reviewed by humans
                      </p>
                    </div>
                    <div className="flex gap-2 pt-1">
                      <Button size="sm" variant="outline">Edit</Button>
                      {t.status !== "approved" && <Button size="sm">Approve</Button>}
                    </div>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
